### ISSUE TITLE
Error in filterCells

### ISSUE THREAD

**Issue by mrichter23** [spcdot/CopyscAT#22]
Hi! I've been trying to run CopyscAT on two data sets. While it's been running fine for the first one, the filterCells function gives me an error for the second one. To me my scData_collapse objects look very similar between data sets, so I'm not sure what is causing the error. Do you have an idea?

scData_collapse<-filterCells(scData_collapse,minimumSegments = 40,minDensity = 0.1)
Error in `dplyr::select()`:
! Can't subset columns that don't exist.
✖ Column `Cell` doesn't exist.

**Comment by spcdot** [comment]
I wonder if it's failing the minimumSegments part, it could be that with a minimum segment density of 0.1 it's losing too many segments (i.e. due to sparse data) and crashing out. I would try dropping minDensity to 0.01 and/or changing minimumSegments to a lower number like 38.

Let me know if that works,

Ana

**Comment by mrichter23** [comment]
Thanks! It was actually that my cell names were not the usual 10X ones and that was what gave me the error :see_no_evil:
